### ISSUE TITLE
Constant annoyance by a chutia chidiya

### ISSUE THREAD

**Issue by saikatbsk** [mister-raindrop/ChutiyaChidiya#1]
I am getting annoyed by the chidiya. Can you please remove it from the game?

**Comment by mister-raindrop** [comment]
It's an intended feature. Besides, if I remove the chidiya, the weight of this chutiyapa will collapse onto itself and implode into the void, which I'd like to avoid. 

Edit: Also, it gets me high.

**Comment by saikatbsk** [comment]
Resolved. Just had to through away my laptop out of the window. Everything's calm now. Life's beautiful.

**Comment by mister-raindrop** [comment]
Closing this as the user has successfully verified the intended feature and emotionally resolved the issue. Thank you for your time.
